const MEAL_EMOJIS: Record<string, string> = {
  breakfast: '🌅',
  lunch: '☀️',
  dinner: '🌙',
  snack: '🍿',
};

const FOOD_KEYWORD_EMOJIS: [RegExp, string][] = [
  [/chicken/i, '🍗'],
  [/turkey/i, '🦃'],
  [/beef|steak|burger/i, '🥩'],
  [/pork|bacon|ham|sausage/i, '🥓'],
  [/fish|salmon|tuna|cod|tilapia/i, '🐟'],
  [/shrimp|prawn|lobster|crab|scallop/i, '🦐'],
  [/egg/i, '🥚'],
  [/rice/i, '🍚'],
  [/pasta|spaghetti|noodle|ramen|linguine|penne/i, '🍝'],
  [/pizza/i, '🍕'],
  [/taco/i, '🌮'],
  [/burrito|wrap/i, '🌯'],
  [/sandwich|sub|hoagie/i, '🥪'],
  [/hot dog/i, '🌭'],
  [/bread|toast|bagel|muffin|croissant|biscuit/i, '🍞'],
  [/pancake|waffle|french toast/i, '🥞'],
  [/cereal|cheerios|flakes|granola/i, '🥣'],
  [/oat/i, '🥣'],
  [/salad/i, '🥗'],
  [/soup|stew|chili/i, '🍲'],
  [/apple/i, '🍎'],
  [/banana/i, '🍌'],
  [/orange|tangerine|mandarin/i, '🍊'],
  [/grape/i, '🍇'],
  [/strawberr/i, '🍓'],
  [/blueberr|berr/i, '🫐'],
  [/watermelon/i, '🍉'],
  [/peach|nectarine/i, '🍑'],
  [/mango/i, '🥭'],
  [/pineapple/i, '🍍'],
  [/avocado|guac/i, '🥑'],
  [/broccoli/i, '🥦'],
  [/carrot/i, '🥕'],
  [/corn/i, '🌽'],
  [/potato|fries|hash brown/i, '🥔'],
  [/sweet potato/i, '🍠'],
  [/tomato|salsa|marinara/i, '🍅'],
  [/pepper|jalapeno/i, '🌶️'],
  [/mushroom/i, '🍄'],
  [/onion|garlic/i, '🧅'],
  [/cheese/i, '🧀'],
  [/milk|cream|yogurt|kefir/i, '🥛'],
  [/butter/i, '🧈'],
  [/ice cream/i, '🍦'],
  [/chocolate|brownie|cocoa/i, '🍫'],
  [/cookie|oreo/i, '🍪'],
  [/cake|cheesecake/i, '🍰'],
  [/donut|doughnut/i, '🍩'],
  [/pie/i, '🥧'],
  [/candy|gummy|skittles|m&m/i, '🍬'],
  [/peanut butter|almond butter|pb/i, '🥜'],
  [/nut|almond|cashew|walnut|pecan/i, '🥜'],
  [/protein shake|protein powder|whey/i, '🥤'],
  [/smoothie/i, '🥤'],
  [/coffee|espresso|latte|cappuccino/i, '☕'],
  [/tea/i, '🍵'],
  [/juice/i, '🧃'],
  [/soda|coke|sprite|pepsi|mountain dew/i, '🥤'],
  [/beer|ipa|lager/i, '🍺'],
  [/wine/i, '🍷'],
  [/cocktail|margarita|vodka|whiskey/i, '🍸'],
  [/water/i, '💧'],
  [/honey/i, '🍯'],
  [/oil|olive/i, '🫒'],
  [/ketchup|mustard|mayo|sauce|dressing/i, '🫙'],
  [/tofu|tempeh|seitan/i, '🫘'],
  [/bean|lentil|chickpea/i, '🫘'],
  [/popcorn/i, '🍿'],
  [/chip|dorito|cheeto|pretzel/i, '🍟'],
  [/mcdonald|burger king|wendy|five guys/i, '🍔'],
  [/chick-fil-a|kfc|popeye/i, '🍗'],
  [/subway/i, '🥪'],
  [/starbucks|dunkin/i, '☕'],
  [/taco bell|chipotle/i, '🌮'],
];

export function getFoodEmoji(foodName: string): string {
  for (const [pattern, emoji] of FOOD_KEYWORD_EMOJIS) {
    if (pattern.test(foodName)) return emoji;
  }
  return '🍽️';
}

export function getMealEmoji(mealType: string): string {
  return MEAL_EMOJIS[mealType] || '🍽️';
}

export const ALL_FOOD_EMOJIS = [
  '🍽️', '🍗', '🥩', '🥓', '🐟', '🦐', '🥚', '🍚', '🍝', '🍕',
  '🌮', '🌯', '🥪', '🌭', '🍞', '🥞', '🥣', '🥗', '🍲', '🍔',
  '🍎', '🍌', '🍊', '🍇', '🍓', '🫐', '🍉', '🍑', '🥭', '🍍',
  '🥑', '🥦', '🥕', '🌽', '🥔', '🍠', '🍅', '🌶️', '🍄', '🧅',
  '🧀', '🥛', '🧈', '🍦', '🍫', '🍪', '🍰', '🍩', '🥧', '🍬',
  '🥜', '🥤', '☕', '🍵', '🧃', '🍺', '🍷', '🍸', '💧', '🍯',
  '🫒', '🫙', '🫘', '🍿', '🍟', '🦃', '🍹', '🧁', '🥐', '🥯',
];
